---
name: Nginx Proxy Manager
version: dev
slug: proxy-manager
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/masrim2000/addon-nginx-proxy-manager2
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:81]
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
  21114/tcp: 21114
  21115/tcp: 21115
  21116/tcp: 21116
  21116/udp: 21116
  21117/tcp: 21117
  21118/tcp: 21118
  21119/tcp: 21119
map:
  - addon_config:rw
backup_exclude:
  - "*/logs"
